@startuml

class CSCStruct <<Struct >> {
    geoHash
    adsress
    csc
}

class CryptoSpatialCoordinate   <<Contract>> {

    +address owner
    {field}+mapping(address->csc) Crypto-Spatial Coordinate
    +<<event>> LogCSCIndexedEntityAdded(cscIndex,geoHash,Owner)
    +<<event>> Deposit(sender, value)
    +<<constructor>> () 
    +<<public>> addCSCIndexedEntity( geoHash) returns ( cscIndex) 
    ~<<pure>> <<intrenal>> calcCSCIndex ( owner,  geoHash) returns () 
    +<<view>> isValidCSCIndex( owner,  geoHash,  cscIndex) returns (bool) 
    +<<view>> isMyCSCIndex( geoHash, cscIndex) returns (bool)     
    +<<external>> function ()   
}

@enduml