@startuml seq-signaling
title sequence : Signaling process
actor User
actor CommunityActors
participant DeLA
database ParcelsIndex


CommunityActors -> DeLA : Offering incentives for land parcels surveying 
DeLA -> DeLA : Mine tokens for \nsignaling round  
DeLA -> User : Notify signaled area
User -> ParcelsIndex : Use mobile application for parcels survey 
ParcelsIndex -> DeLA : Register User contribution
DeLA -> User : Reward
DeLA -> CommunityActors : Notify contribution

@enduml