@startuml seq-foam
title sequence : FOAM protocole
actor User
participant Web3App
participant CSCSmartContract
participant Backend
database FeaturesIndex

User -> Web3App : Add Feature
Web3App -> CSCSmartContract : Call CSC smart contract
CSCSmartContract -> Web3App : Log Add CSC Feature event
CSCSmartContract -> Backend : Log Add CSC Feature event
Backend -> FeaturesIndex : Add the Feature to the Index
Web3App -> Backend : Fetch Features Index 
Backend -> FeaturesIndex : Fetch Features Index 
FeaturesIndex -> Backend : List of Features 
Backend -> Web3App : Return saved Features
Web3App -> User : Show FeaturesIndex on a map
@enduml