@startuml
actor user
participant web3App
participant ethereum
participant backend
database indexes

user -> web3App : Add Index
web3App -> ethereum : Call CSC smart contract
ethereum -> web3App : Log Add CSC index event
web3App -> backend : Add the Index to the database
backend -> indexes : Create a new record
web3App -> backend : Fetch indexes 
backend -> web3App : Return saved indexes
web3App -> user : Show indexes on a map
@enduml